name: check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  NODE_VERSION: '22'
  PYTHON_VERSION: '3.13'

permissions:
  contents: read

jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: install dependencies
        run: sudo apt install -y lcov astyle
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd c && make version build
      #- name: coverage report
      #  uses: coverallsapp/github-action@v2
      #  with:
      #    format: lcov
      #    file: c/target/test/coverage/variantkey.info

  go:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup go build environment
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd go && make mod deps linter test GOPATH=$(go env GOPATH)

  javascript:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup node build environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install dependencies
        run: npm install --global uglify-js js-beautify
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd javascript && make build

  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python build environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools virtualenv
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd python && make all

  python-class:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python build environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools virtualenv
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd python-class && make all

  r:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup R build environment
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: './r/variantkey/'
          cache-version: 2
          extra-packages: |
            any::Rcpp
            any::devtools
            any::inline
            any::renv
            any::roxygen2
            any::testthat
            any::pkgdown
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd r && make build test
